version: '3.8'

services:
  django-template:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - django_template
    ports:
      - 8000:8000
    env_file:
      - ./.env

networks:
  django_template: