version: '3.8'

services:
  postgres:
    networks:
      - django_template
    image: postgres:12-alpine
    ports:
      - ${PG_PORT}:5432
    environment:
      - DEBUG=true
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}

networks:
    django_template: